### PR TITLE
Add Point class

### PR DESCRIPTION
**Pull request by Sedictious**
Returning a vector for anything can be a bit confusing and I think a Point class might come in handy. Note that I did this pretty quickly so there may be a few mistakes :)

### CODE REVIEW

**Comment by 20chan** [comment]
Is there any differences between `Vector` and `Point`? It seems like `Point` class is just an alias of `Vector`.

**Comment by Sedictious** [comment]
@20chan Geometrically, a ``Vector`` specifies a direction/displacement while a ``Point`` specifies a location in space. They can have slightly different behavior (e.g adding Vectors makes sense but you can not add Points), but the ``Vector`` class could still be used interchangeably.  It's mainly a semantic difference though, so I understand if you only wanted to keep the ``Vector`` class to avoid confusion.

**Comment by 20chan** [comment]
I understand what you wanted to do, but we just can't recreate exact same as `Vector` struct, named in `Point` to explain what returned value is for, like, direction or location. It is just a duplicated code, which is not recommended styles.

For example,

```csharp
Vector GetDirections***();
Vector GetLocation***();
```

These two methods returns same `Vector` struct, but we all know what their value really means. Its name already explained what their value means, and it is much efficient than using two EXACT same structures.

It is just same as `Vector2` in unity, or slightly different but `Vector` class in c++, it does not matter what really `Vector` was used for.

If it was rust, not c#, we could use type alias like this and I guess it was what you wanted.

```rust
type Point=Vector2D;
type Vector=Vector2D;
```

**Comment by Sedictious** [comment]
@20chan
Yes I thought about using inheritance (so ``Vector`` and ``Point`` would inherit from something like ``Tuple``) but I think it's a bit of an overkill. The two aren't the exact same, but their differences are minute (like I mentioned, there's no addition of points, neither can you take the cross/dot product of different points). But I think you're right and having two closely related classes would lead to not only code duplication, but make the code a bit more complicated as well.

**Pull request closed without merging**
